[package]
name = "framecounter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macaddr = "1.0.1"
pcap = "1.3.0"
radiotap = "1.3.0"
